### ISSUE TITLE
runmaf function

### ISSUE THREAD

**Issue by XuanYuXu** [getzlab/getzlab-SignatureAnalyzer#16]
Angone can tell me why it happened?I do not what to do 

In [10]: sa.run_maf('input.maf' , outdir='./ardnmf_output/', cosmic='cosmic2', hg_build='./ref/hg19.2bit', nruns=10)
   * Creating output dir at ./ardnmf_output/
   * Using hg19 build
   * Using cosmic2 signatures
   * Loading spectra from input.maf
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-10-bf1b3428f79c> in <module>
----> 1 sa.run_maf('input.maf' , outdir='./ardnmf_output/', cosmic='cosmic2', hg_build='./ref/hg19.2bit', nruns=10)

C:\Anaconda3\lib\site-packages\signatureanalyzer\signatureanalyzer.py in run_maf(maf, outdir, cosmic, hg_build, nruns, verbose, plot_results, **nmf_kwargs)
     83     print("   * Loading spectra from {}".format(maf))
     84     maf, spectra = get_spectra_from_maf(
---> 85         pd.read_csv(maf, sep='\t'),
     86         hgfile=hg_build,
     87         cosmic=cosmic

C:\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675
--> 676         return _read(filepath_or_buffer, kwds)
    677
    678     parser_f.__name__ = name

C:\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    452
    453     try:
--> 454         data = parser.read(nrows)
    455     finally:
    456         parser.close()

C:\Anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   1131     def read(self, nrows=None):
   1132         nrows = _validate_integer("nrows", nrows)
-> 1133         ret = self._engine.read(nrows)
   1134
   1135         # May alter columns / col_dict

C:\Anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   2035     def read(self, nrows=None):
   2036         try:
-> 2037             data = self._reader.read(nrows)
   2038         except StopIteration:
   2039             if self._first_chunk:

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 120

**Comment by shankara-a** [comment]
Hi,

Could you please clarify your inputs. I am not sure what is in 'input.maf'.
