### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by mishugeb** [getzlab/getzlab-SignatureAnalyzer#24]
This is a question rather than an issue. What mutational contexts we can use for extraction? For example, can we extract signatures beyond SBS96, DBS, and INDELs? I am asking because got an error when I tried to extract signatures from a 1673 context.   

Thanks in advance

**Comment by kimin0402** [comment]
Hi mishugeb, I'm not a developer of siganalyzer, but recognize your name from the sigprofiler package. 

Just out of curiosity, how can you get 1673 context? It's 7 times 239, and I can't imagine how those numbers could be related to genomic mutations.

**Comment by mishugeb** [comment]
It's an arbitrary number. I meant can I extract signatures from a matrix that has 1673 rows or any n rows where n is a positive integer.

**Comment by shankara-a** [comment]
You can run the algorithm itself on any input spectra you wish to decompose.

For extraction methods, in our public release we only provide extraction from `.maf` for SBS96, DBS, and INDELS, but we are in the process of adding more.
