### ISSUE TITLE
Removal of SBS84, SBS85 from supervised example?

### ISSUE THREAD

**Issue by DoaneAS** [getzlab/getzlab-SignatureAnalyzer#35]
Hi,

Thanks for this work- for the most part it's working nicely, however I'm not sure why you remove the last 2 cosmic3 signatures in the supervised tutorial:

```
# Subset reference data to create W matrix
Wref_df = ref_df.set_index('Somatic Mutation Type').iloc[:,:-2]
```
Perhaps for cosmic data you meant:
```
ref_df.set_index('Somatic Mutation Type').iloc[:,2:]
```

**Comment by shankara-a** [comment]
Hi @DoaneAS - I believe when I wrote this I was dropping the `max_id` and `max_norm` column that is automatically added when `signatureanalyzer` is initially run. Good catch that this would drop columns on reference data that does not have those columns.

**Comment by DoaneAS** [comment]
Hi @shankara-a, thanks- figured it was something like that.  Thanks for SignatureAnalyzer!
