### ISSUE TITLE
KeyError: 'Tumor_Sample_Barcode'

### ISSUE THREAD

**Issue by ksingh1119** [getzlab/getzlab-SignatureAnalyzer#36]
<img width="1203" alt="Screen Shot 2021-11-08 at 10 59 57 PM" src="https://user-images.githubusercontent.com/93730890/140877257-500e9249-904d-444f-87de-cdd9166a0c4e.png">

Hi,

I keep getting this key error although my MAF file has a column for the Tumor_Sample_Barcode, any suggestions on the fix. I've also attached a screenshot of the MAF file. Thanks for your help in advance!

**Comment by shankara-a** [comment]
Hi @ksingh1119 ,

The `Tumor_Sample_Barcode` should be unique sample/patient ID in your `.maf`. For the input to the algorithm, it generates spectra _per patient_ - meaning we have (patients x 96 SBS spectra, for example). Thus, it uses the `Tumor_Sample_Barcode` to assign mutations to samples.

Does your `.maf` only have one sample? If so, you might not have enough samples to perform decomposition with `ard-nmf`. I might recommend a [supervised](https://github.com/getzlab/getzlab-SignatureAnalyzer/blob/master/signatureanalyzer/Supervised_HowTo.ipynb) approach.

Please let me know if you have any other questions!

Shankara

**Comment by ksingh1119** [comment]
HI,

Thank you so much for your quick response. I am running only one sample at
this time for testing purposes and I will try the supervised approach and
see if that works. Thanks for your help again and will reach out if I have
any issues.

Kind Regards,
Kunwar

**Comment by ksingh1119** [comment]
Apologies for the repeat question but I now running into the following
issue running the supervised script in python :

AttributeError: module 'signatureanalyzer' has no attribute 'spectra'


Any suggested work around?


Thanks!

**Comment by ksingh1119** [comment]
Sorry I resolved that error but I keep getting this reference error am I
supposed to change the reference directory?


TypeError: get_spectra_from_maf() got an unexpected keyword argument
'reference'

**Comment by shankara-a** [comment]
Are you using the most up to date version? 
Maybe try installing the dev version with these instructions: 
https://github.com/getzlab/getzlab-SignatureAnalyzer#git-clone

The function call has the`reference` kwarg:
https://github.com/getzlab/getzlab-SignatureAnalyzer/blob/94c8a98209c400095862b538b843d82ea47dd8b9/signatureanalyzer/spectra.py#L10

**Comment by ksingh1119** [comment]
Hi,

I believe I was using the most updated version, I just cloned the dev
version and tried to run the same supervised code in python and I am
getting the original error message of tumor_sampel_barcode.  Should I go
back and install the pip3 version and are my pathways correct? Thanks for
your help and appreciate you getting back to me so quickly. Have a
wonderful day!


>>> import pandas as pd

>>> import signatureanalyzer as sa

>>> REF=
"/users/kunwarsingh/getzlab-signatureanalyzer/signatureanalyzer/ref/cosmic_V3"

>>> REF_PATH =
"/users/kunwarsingh/getzlab-signatureanalyzer/signatureanalyzer/ref/cosmic_V3/sa_cosmic3_sbs_exome.tsv">>>
MAF_PATH = "/users/kunwarsingh/output-hg38/CCGL/CCGL_somatic.maf"

>>> HG_PATH = "/users/kunwarsingh/hg38.2bit"

>>> SIG_LIST = ['SBS1','SBS2','SBS3']

>>> MAX_ITER = 30000

spectra_df = sa.spectra.get_spectra_from_maf(maf, hgfile=HG_PATH,
reference=REF)[1]

Traceback (most recent call last):

  File
"/Users/kunwarsingh/Library/Python/3.9/lib/python/site-packages/pandas/core/indexes/base.py",
line 3361, in get_loc

    return self._engine.get_loc(casted_key)

  File "pandas/_libs/index.pyx", line 76, in
pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 108, in
pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in
pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in
pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'Tumor_Sample_Barcode'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File
"/Users/kunwarsingh/getzlab-SignatureAnalyzer/signatureanalyzer/spectra.py",
line 33, in get_spectra_from_maf

    maf['sample'] = maf['Tumor_Sample_Barcode']

  File
"/Users/kunwarsingh/Library/Python/3.9/lib/python/site-packages/pandas/core/frame.py",
line 3458, in __getitem__

    indexer = self.columns.get_loc(key)

  File
"/Users/kunwarsingh/Library/Python/3.9/lib/python/site-packages/pandas/core/indexes/base.py",
line 3363, in get_loc

    raise KeyError(key) from err

KeyError: 'Tumor_Sample_Barcode'

**Comment by ksingh1119** [comment]
Also I attached my MAF file to this email, thanks!

**Comment by ksingh1119** [comment]
Good morning,

I just wanted to follow up if you have any suggestions on how to fix this
issue, thank you for your help and I hope you have a wonderful day!

Kunwar

**Comment by yoakiyama** [comment]
Your input MAF file needs to have "Tumor_Sample_Barcode" as a column that
labels each variant with a sample ID. This should fix your issue.

Yo
